# Site settings
title: devcave.pl
email: lasota.marcinm@gmail.com
copyright_name: devcave
description: "Devcave - jaskinia programisty. Blog programisty na tematy związane z branżą IT, a szczególnie z programowaniem. Pracuję głownie z językami Java i Javascript, ale na blogu nie zabraknie tematów ogólnych, z życia wziętych ;)"
baseurl: ""
url: "https://devcave.pl"
github_username:  C0deboy
email_username: lasota.marcinm@gmail.com
# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-90973428-2

collections:
- top_posts

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "npm-debug.log", "Gemfile", "Gemfile.lock", "package-lock.json","js", "css"]
include: ["_pages"]
plugins: [jekyll-paginate, jekyll-feed, rouge, jekyll-sitemap, jekyll-toc]
