# Site settings
title: devcave.pl
email: lasota.marcinm@gmail.com
copyright_name: devcave
description: "Devcave - blog programisty na tematy związane z branżą IT, a szczególnie z programowaniem w Javie."
url: "https://devcave.pl"
github_username:  C0deboy
email_username: lasota.marcinm@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title
paginate: 5
exclude: ["node_modules","webpack.config.js","package.json","README.md", "npm-debug.log", "Gemfile", "Gemfile.lock", "package-lock.json", ".idea"]
include: ["_pages"]
keep_files: [.git, .gitignore, CNAME]
plugins: [jekyll-paginate, jekyll-feed, rouge, jekyll-sitemap, jekyll-toc, jemoji]
